### ISSUE TITLE
Initialization and restart

### ISSUE THREAD

**Issue by totto82** [OPM/opm-core#1004]
Currently FLOW computes the initial state also for restart runs. This would not be a big problem ( other than some wasted calculations), if not for the fact that somehow Eclipse gives an error if EQUIL or other initialization related keywords is specified in Restart runs.

**Comment by joakim-hove** [comment]
I have added this as a comment to: https://github.com/OPM/opm-parser/issues/773 - that is in my opinion the right place to discuss this. The actual `EQUIL` initialization is performed here in opm-core, but the decision whether to do it or not - is taken in opm-parser.
