### ISSUE TITLE
Failing test_relpermdiagnostics

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-core#1007]
The test currently fails by throwing an exception in constructing an EclipseGrid object:
```
unknown location:0: fatal error in "diagnosis": std::invalid_argument: The RUNSPEC section must have the DIMENS keyword with logically Cartesian grid dimensions.
```

This is triggered from EclipseGrid.cpp line 132. The deck is the file relpermDiagnostics.DATA which indeed has a DIMENS keyword, so I do not understand this. This also fails in Travis right now, preventing any Travis runs from succeeding. @joakim-hove or @qilicun, can you investigate this please?

**Comment by joakim-hove** [comment]
We are on it, it is a parse error related to empty title.
3. mai 2016 15:00 skrev "Atgeirr Flø Rasmussen" <notifications@github.com>
følgende:

**Comment by jokva** [comment]
Ye, the error has been identified and a fix is being written.

**Comment by jokva** [comment]
https://github.com/OPM/opm-parser/pull/792 Should fix this.

**Comment by atgeirr** [comment]
> Should fix this

It did, thanks!
