### ISSUE TITLE
opm-core build fails

### ISSUE THREAD

**Issue by pgdr** [OPM/opm-core#1020]
opm-core build fails.  I don't know what's the reason, nor why Travis is green.  But Jenkins fails and I can't build it either.

    /var/jenkins/workspace/opm-core-install-RH6/examples/compute_initial_state.cpp: In function ‘void {anonymous}::outputData(const string&, const string&, const std::vector<double>&)’:
    /var/jenkins/workspace/opm-core-install-RH6/examples/compute_initial_state.cpp:64:28: error: variable ‘std::ofstream file’ has initializer but incomplete type
             std::ofstream file(fname.str().c_str());
                                ^
    Linking CXX executable bin/tutorial4
    /var/jenkins/workspace/opm-core-install-RH6/examples/compute_tof_from_files.cpp: In function ‘int main(int, char**)’:
    /var/jenkins/workspace/opm-core-install-RH6/examples/compute_tof_from_files.cpp:89:35: error: variable ‘std::ifstream poro_stream’ has initializer but incomplete type
             std::ifstream poro_stream(param.get<std::string>("poro_filename").c_str());

**Comment by blattms** [comment]
I experienced the same fixed with PR #1021 here and OPM/opm-simulators#699 in simulators.

**Comment by blattms** [comment]
travis does not find ERT. No idea why.

Are you sure you are using my branch? I definitely fixed that file:

```
mblatt@loft11004:~/DUNE-test/opm-core$ grep fstream
examples/compute_initial_state.cpp
#include <fstream>
std::ofstream file(fname.str().c_str());
blatt@loft11004:~/DUNE-test/opm-core$ git diff
blatt@loft11004:~/DUNE-test/opm-core$
```
and pushed the changes.

**Comment by jokva** [comment]
There's a PR on it in common. The ERT C++ interface was changed, and the the one changed bit was the one checked by FindERT.cmake in common. Apply https://github.com/OPM/opm-common/pull/125 and it should be fine.

**Comment by pgdr** [comment]
100% tests passed, 0 tests failed out of 38
