### ISSUE TITLE
Allow passing the size of the initial time step to adaptive time stepper

### ISSUE THREAD

**Issue by blattms** [OPM/opm-core#1033]
If I restart a simulation, then I want to be able to use same suggested timestep for a simulation step as it would have been used for a full run. Currently, I can only request flow to use the full time step initially, but that would start each step with the full time, right?
At least for debugging this would be very useful.

**Comment by atgeirr** [comment]
I think with recently added partial support for the TUNING keyword, this can be done now. The features were implemented in #1076 and OPM/opm-simulators#843. Basically you have to pass "use_TUNING=true", and then the sim will check the TUNING keyword of the deck. The first entry of TUNING is TSINIT, the max size of the next timestep (the rest can be defaulted).

Closing the issue, please reopen if it is not working.
