### ISSUE TITLE
Runtime failure in "linsolver" test - umfpack not configured

### ISSUE THREAD

**Issue by flikka** [OPM/opm-core#1036]
When building via the `build-prereqs.sh`, `clone-opm.sh` and `build-and-test.sh` that lies in the opm-common - I ran in to a situation where the build (or rather the test) failed in opm-core. 

The underlying cause was that I had not installed the suitesparse package. The `HAVE_UMFPACK` and `HAVE_SUITESPARSE_UMFPACK_H` were not set.

I don't know if this should be "fixed" by having an `ifdef` before the test in question (`DefaultTest`), or if it something that should be done in the `LinearSolverFactory`, or something else (or nothing).

Just mentioning this, to hear if anything should be done.

**Comment by atgeirr** [comment]
If you don't have UMFPACK it is unfortunate that it is still the default for the LinearSolverFactory. I think we should fix that.

**Comment by atgeirr** [comment]
Resolved in #1040.
