### ISSUE TITLE
WellState::init has memory problems

### ISSUE THREAD

**Issue by blattms** [OPM/opm-core#1066]
I just ran SPE1 in parallel. In this case the situation occurs that the last (second of two) wells has no connections and memory bounds are violated in https://github.com/OPM/opm-core/blob/ce78dc5560a492f1e89d64caa1c0816723ed1a9e/opm/core/simulator/WellState.hpp#L134
The  problem is that `wells->well_connpos[1]` is 1 and that is also the size of the `wells->well_cells` array.

As I do not have the complete overview on the well treatment I would like to get some input here. Shall we either disregard wells with no connections completely here or treat them like a wells for which `well_controls_get_current_type(ctrl) == BHP` holds?

BTW this feels like a Déjà vu

**Comment by blattms** [comment]
Same issue here:
https://github.com/OPM/opm-core/blob/ce78dc5560a492f1e89d64caa1c0816723ed1a9e/opm/core/simulator/WellState.hpp#L94
Not sure whether this handled correctly for multi segment wells.

**Comment by blattms** [comment]
Even for sequential runs we could have this situation if the last well is shut and all compeltions are in non-active cells.

**Comment by atgeirr** [comment]
> BTW this feels like a Déjà vu

Not again...?

Joke aside, I think we should disregard wells with no connections completely. The initialization code makes no sense for such wells, and should not be needed as the wells are not connected in any way with the rest of the problem.

I am not quite sure what happens to such wells in the simulator though -- I thought that at some point such wells would be treated as shut and totally ignored, but that may not be 100% correct. In any case, initializing their bhps with a simple default (1 atmosphere?) should not do any harm as it should never interact with the rest of the problem. A slightly more sophisticated way may be to see if the connection-less well has a bhp control, and use that limit (currently that is only used if bhp is the current active control).

**Comment by blattms** [comment]
I guess this is connected to output. If we totally neglect them then they will not appear there (no well curves).

There also might be cases where perforations appear at a later stage or vanish. Therefore a well with no valid perforations might have some at another point in the simulation.

**Comment by atgeirr** [comment]
Wells can shut, open, shut again etc. so if they participate in the simulation can change. The point about how output treats this is a good one: should we arbitrary insert zeros for bhps of shut wells in the output for example? Perhaps @joakim-hove can shed a little light on this issue?

**Comment by blattms** [comment]
I will repeat myself here, too (sorry for the noise).

The problem I experienced was caused by buggy opm-grid loadbalancing code that was never in master.

Still there are situations where we can have open wells which have open wells according to eclipse but all of them get closed by the simulator because they are on inactive cells or the Limiter `DynamicListEconLimited`tells it to shut them in [`WellsManager::createWellsFromSpec`](https://github.com/OPM/opm-core/blob/ce78dc5560a492f1e89d64caa1c0816723ed1a9e/opm/core/wells/WellsManager_impl.hpp#L169-L191). This situation has to be handled somehow

**Comment by blattms** [comment]
Should be fixed with the merge of #1067
