### ISSUE TITLE
Don't we need to keep track of (artificially) shut completions in the simulator for output?

### ISSUE THREAD

**Issue by blattms** [OPM/opm-core#1074]
Looking at the various PRs that extend ouput such that it writes all the well information the following question keeps bothering me.

Currently, the eclipse parser reads the well information and it gets passed to the WellsManager as is. The WellsManager does the following filtering:
1. Remove shut wells.
2. For each open well it removes all shut completions.
3. For each open well it removes all completions that are not in active cells. Active means there is no cartesian to compressed index mapping for the cell
4. It removes all completions that the DynamicListEconLimited tells it to shut.

The code is [here](/OPM/opm-core/blob/ce78dc5560a492f1e89d64caa1c0816723ed1a9e/opm/core/wells/WellsManager_impl.hpp#L169-L193).

1-2 can be done with information of the eclipse file.
I am not totally sure about 3. What  happens if a cartesian cell gets merged (or is it pinched?) with another one. If it only retains one cartesian index then this completion  might ignored even if the cell is actually active. Can this be judged and resolved by inspecting the eclipse file only?
What about 4? Can the ouput layer really know that this happens?

It  seems to me that perforation rate and other data arrays whose size depends on the number of open perforations get passed to opm-output directly. If any of above points cannot be determined by the eclipse information alone then these arrays might be shorter than expected by the output layer. In this case we might need to pass information about artificially shut completions along with the data.

**Comment by blattms** [comment]
I assume this has been resolved by the refactoring of opm-output?

**Comment by jokva** [comment]
If data for a completion isn't given to output it will just output zeros instead, so yes.

**Comment by blattms** [comment]
Closed by the recently refactoring of opm-output
