### ISSUE TITLE
Broken test

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-core#1148]
Ok - I realise now that opm-parser recently broke the EQUIl test here in opm-core, I am sorry about this. Will look into it tomorrow, but I foresee I already now that I might need some assistance. Feel free to merge a revert in opm-parser.

**Comment by alfbr** [comment]
Be aware that the PR fixed a critical bug. I would rather prefer disabling the test than reverting the PR while the investigation is ongoing.

**Comment by joakim-hove** [comment]
@totto82  /  @andlaus : can you look into this; I really do not have a clue whether this is a bug/regression in the code, or if the test needs to be updated; but since this seems to come from the merging of: https://github.com/OPM/opm-parser/pull/1051 you might know how this should be fixed.

**Comment by totto82** [comment]
I had a quick look. The test needs to be updated. Sorry for late replay. I was traveling. Expect a fix tomorrow.
