### ISSUE TITLE
Some files missing?

### ISSUE THREAD

**Issue by sogoogos** [OPM/opm-core#1213]
Hello, when I tried to compile the master branch, I got:
```
[ 21%] Making "tests" data available in output tree
[ 21%] Built target datafiles
[ 22%] Building CXX object CMakeFiles/opmcore.dir/opm/core/flowdiagnostics/DGBasis.cpp.o
[ 22%] Building CXX object CMakeFiles/opmcore.dir/opm/core/flowdiagnostics/AnisotropicEikonal.cpp.o
In file included from /Volumes/Transcend/rmine/OPM_20180221/opm-core/opm/core/flowdiagnostics/AnisotropicEikonal.cpp:21:
/Volumes/Transcend/rmine/OPM_20180221/opm-core/opm/core/flowdiagnostics/AnisotropicEikonal.hpp:23:10: fatal error: 'opm/core/utility/SparseTable.hpp' file not found
#include <opm/core/utility/SparseTable.hpp>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Volumes/Transcend/rmine/OPM_20180221/opm-core/opm/core/flowdiagnostics/DGBasis.cpp:22:10: fatal error: 'opm/core/grid.h' file not found
#include <opm/core/grid.h>
```
I think some files are missing to compile it.

**Comment by bska** [comment]
The opm-core module is no longer supported (or needed).  You should be able to build the entire OPM module stack up to and including opm-simulators (or opm-upscaling) without building opm-core.  The opm-core module was marked "deprecated" in Pull Request #1212 on the 17th of January of this year.

If you experience build problems **without** trying to build module opm-core then please let us know.

**Comment by sogoogos** [comment]
Oh okay, thank you for your reply. I was able to build all the modules without opm-cores.
