### ISSUE TITLE
Grid file is written as formatted data by writeECLdata()

### ISSUE THREAD

**Issue by laods** [OPM/opm-core#236]
Commit 1281d17 made writeECLdata() write restart files unformatted by default. However, the produced grid file (.FEGRID) is still written as formatted by default. Should this also be changed? It would also be nice if a .INIT file is written by writeECLdata(), so that the static variables can be accessed.

**Comment by atgeirr** [comment]
Is this issue still relevant? Since our current eclipse-format output capabilities are far better than they were at the time this issue was created, I suspect that it can be closed.

**Comment by joakim-hove** [comment]
I consider this issue resolved/completely out of date.

Closing.
