### ISSUE TITLE
Linker problem when building with MPI

### ISSUE THREAD

**Issue by laods** [OPM/opm-core#281]
As I am trying to build OPM with MPI enabled, I have met some obstacles. When building on RHEL5 everything builds fine when setting `USE_MPI=ON`. But on RHEL6 we don't have the MPI library in a standard location, and thus I have to specify be path explicitly. I am doing this with `_MPI_PREFIX_PATH` (I think @rolk told me so some time ago). My call to `cmake` is:

    cmake -DDUNE_ROOT="/project/res/x86_64_RH_6/share/opm/dune" \
    -DSUPERLU_ROOT="/project/res/x86_64_RH_6/share/opm/SuperLU_4.0" \
    -DUSE_MPI=ON -D_MPI_PREFIX_PATH="/prog/sdpsoft/openmpi-1.6.3" ../

However, now the configuration process can't find dune-common or dune-istl anymore (even though the reported `DUNE_COMMON_ROOT` is correct):

```
-- Finding package MPI using module mode
-- Found MPI_C: /prog/sdpsoft/openmpi-1.6.3/lib/libmpi.so  
-- Found MPI_CXX: /prog/sdpsoft/openmpi-1.6.3/lib/libmpi.so;/prog/sdpsoft/openmpi-1.6.3/lib/libmpi_cxx.so  
-- Performing Test HAVE_DUNE_COMMON
-- Performing Test HAVE_DUNE_COMMON - Failed
DUNE_COMMON_ROOT = /project/res/x86_64_RH_6/share/opm/dune/dune-common
-- Could NOT find dune-common (missing:  HAVE_DUNE_COMMON) 
```

I find this error message a bit strange as dune-common and istl is found if `_MPI_PREFIX_PATH` is not set.

**Comment by atgeirr** [comment]
Since the issue is old, inactive and has not been reproduced by others, I will close it. Reopen if necessary.
