### ISSUE TITLE
Property objects for autodiff and core have partially inconsistent interfaces

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-core#438]
for example, the current API for relative permeability in autodiff is

```
        virtual
        std::vector<V> relperm(const V& sw,
                               const V& so,
                               const V& sg,
                               const Cells& cells) const;
```

while it is

```
        virtual void relperm(const int n,
                             const double* s,
                             const int* cells,
                             double* kr,
                             double* dkrds) const;
```

in core. If I understood this correctly, the s array in core is a pointer of numCells arrays each consisting of the canonical saturations of each cell. On the other side of the fence, the autodiff interface uses three separate arrays for the canonical phase saturations. In both cases, this kind of interface requires to jump through hops if the saturations from the BlackoilState class ought to be used because this one only contains a concatenated array of the saturations of the used phases.

If I understood this correctly, it even gets worse in the AD interface which also contains the method

```
 std::vector<ADB> relperm(const ADB& sw,
                                 const ADB& so,
                                 const ADB& sg,
                                 const Cells& cells) const
```

which requires AutoDiffBlocks for _all_ saturations as input but only produces an AutoDiffBlock for the _used_ phases.

synopsis: I'm confused...

**Comment by atgeirr** [comment]
While the differences in interface are real and regrettable, I will postpone this issue as it is not something we are going to fix short of a major refactoring.

That refactoring however, *is* going to happen, hopefully before the fall release.

**Comment by atgeirr** [comment]
I will close this, as it is not something we can or will target, specifically. The issue discussed is still relevant, but the matter is larger: the property systems should be continuously refactored. The underlying dilemma between assuming AD types or not in the interface will no go away.
