### ISSUE TITLE
Initial data not handled in EclipseWriter with inactive blocks

### ISSUE THREAD

**Issue by rolk** [OPM/opm-core#455]
Eclipse initialization file only contains data for active cells (see for instance comment 
https://github.com/OPM/opm-core/pull/424#issuecomment-28472181), but the PORO data is retrived from the parsing of the input file, which contains the full data set. This causes an ERT error.

The fix is probably to do an indirect lookup in this array through the global_cell field of the grid_ member (if non-null).

**Comment by atgeirr** [comment]
This is an old issue, but I hope we can close it as fixed? I am in any case not going to pursue it for the upcoming release.

**Comment by atgeirr** [comment]
This issue is no longer relevant:
 - original problem no longer occurs
 - other problem from discussion has its own issue (#878)
 - problems with the EclipseWriter should be discussed in opm-output
