### ISSUE TITLE
problem for creating grid

### ISSUE THREAD

**Issue by qilicun** [OPM/opm-core#461]
Hi，
I have to do a test which grid is 1*1*300, but all the simulator are aborted.
The problem seems  caused by Opm::GridManager::initFromDeckTensorgrid().
Does anyone can reproduce this issue and see what's the problem?

Thanks.

**Comment by atgeirr** [comment]
Can this issue be closed @qilicun?

**Comment by qilicun** [comment]
Yes, the problem is solved, thanks! I will close it.
