### ISSUE TITLE
Problem in compiling

### ISSUE THREAD

**Issue by mahdi25** [OPM/opm-core#567]
I'm trying to compile a test program(sim_2p_incomp.cpp) but I am not successful. 
I enter the following commands: 

g++ -c -I/usr/local/include sim_2p_incomp.cpp

g++ -o sim_2p_incomp.o -L/usr/local/lib/x86_64-linux-gnu -lopmcore

error:
g++ -o sim_2p_incomp.o -L/usr/local/lib/x86_64-linux-gnu -lopmcore
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu/crt1.o: In function '_start':
(.text+0x20): undefined reference to 'main'
collect2: ld returned 1 exit status

Please help me
How to compile&link a file(sim_2p_incomp.cpp)?

**Comment by atgeirr** [comment]
Since there has been no replies or activity on this I will close the issue. Reopen if necessary.
