### ISSUE TITLE
Add Petsc to opm-core

### ISSUE THREAD

**Issue by qilicun** [OPM/opm-core#588]
Hi all,
This week I add [Petsc](http://www.mcs.anl.gov/petsc/)(which is a powerful linsolver package, have lots of ksp solvers and preconditioners, very easily to change solver and pc type from command line) to opm-core, ``FindPetsc.cmake`` is made for congfigure and it works well, and also I implement the interface for Petsc, which are ``call_petsc.c`` and ``LinearSolverPetsc.cpp``, through a very simple test, I think the interface has no big(seen) bugs. But there are two more problems need to be solved.
- The initialize function in Petsc need two arguments, ``int argc, char** argv``, How can I get them from ``ParametersGroup``? Or just directly create a construct function named ``LinearSolverPetsc(int argc, char** argv)``?(this is the way I do for testing).
- There must be some magic for cmake, because I want opm-polymer call ``LinearSolverPetsc``, error happened, such like this 
```
/lib/libopmcore.a(call_petsc.c.o): In function `call_Petsc':
opm/core/linalg/call_petsc.c:166: undefined reference to `PetscInitialize'
```
It seems libpetsc.a doesn't linked to libopmcore.a? I am out of ignorance of cmake and ld stuff... hope you can help me :)

**Comment by atgeirr** [comment]
PETSc support has been added and this discussion has been superseded by concrete PRs, so I'll close this issue.
