### ISSUE TITLE
Discussion: 3D properties and SECTION awareness

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-core#594]
Hello;

with the PR: https://github.com/OPM/opm-parser/pull/226 the parser supports the BOX keyword and the property modifier keywords ADD, COPY, EQUALS and MULTIPLY. Following this PR we can now write:
```C++
GridPropertry<double> permx = eclipseState->getDoubleProperty("PERMX");
```
and get a `GridProperty<double>` object where all modifiers++ found in the deck have been correctly applied. 

When working with this implementation it has become quite clear that the opm-parser has a quite low awareness of sections. For instance the `FIPNUM` keyword and modifiers on that keyword should according to the manual only occur in the `REGIONS` section, whereas the current opm-parser implementation will accept `FIPNUM` and `FIPNUM` modifications anywhere in the code; so currently the opm-parser is actually less strict than ECLIPSE.

My suspicion is that ECLIPSE never really internalizes the Deck; it does a first pass to check that keywords are recognized, include files found e.t.c. and then it starts interpreting the .DATA file like a highly imperative programming language. In that situation it seems reasonable to require a quite strong division of the .DATA file in different sections; as I see it that is not necessary for opm.

So the question is essentially: "Should we allow the opm-parser to be more relaxed than ECLIPSE when it comes to locating keywords in different sections in the .DATA file?"

**Comment by atgeirr** [comment]
As far as I know this is working well for both simulation and upscaling. Closing.
