### ISSUE TITLE
opm-parser find rule is broken

### ISSUE THREAD

**Issue by akva2** [OPM/opm-core#597]
The opm parser find rule is broken. If parser is built with ERT support, ERT is not added to the list of dependencies.

If you static link, link order is important. So even though the main library links against ERT, it ends up too early in the list (which is processed backwards).

A simple fix is just to add ERT_LIBRARIES to the OPM_PARSER_LIBRARIES, but i wanted to ask why the find rule isn't "normal", i.e. use opm_find etc ? the prereqs file is unused for instance..

**Comment by andlaus** [comment]
this seems to be fixed with #599. if this is not the case, please reopen the issue...
