### ISSUE TITLE
Handling of wells that are shut.

### ISSUE THREAD

**Issue by dr-robertk** [OPM/opm-core#667]
Currently the NORNE deck fails to run (seg fault) because there are various bugs spread out in opm-core and opm-autodiff. The seg fault happens whenever something like well_controls_get_current_type is called for a well that was actually shut. In line 60 of the file 
opm/core/simulator/WellState.hpp there is one occasion where this happens. 

The question is: What to do here? Should the Assign bhp equal to bhp control branch be removed?

**Comment by atgeirr** [comment]
This issue has long been resolved, so I'll close this issue.
