### ISSUE TITLE
symbol lookup error ecl_grid_alloc_dx_dy_dz_tops with wells_example.cpp

### ISSUE THREAD

**Issue by TobiasRitschel** [OPM/opm-core#780]
I have been trying to compile and run the `wells_example.cpp` from opm-core. I created a `data.data` file where I specify the RUNSPEC and GRID sections. It compiles fine but when I run it I get the following error:
```
inputdeck not found. Using default value 'data.data'.
num_psteps not found. Using default value '1'.
stepsize_days not found. Using default value '1'.
./wells_example: symbol lookup error: ./wells_example: undefined symbol: ecl_grid_alloc_dx_dy_dz_tops
```
The first three lines seems fine to me, but searching for this symbol on the last line on Google gives 3 hits of which 2 are other issues. One says to update ERT and the other is related to opm-autodiff.

I installed ERT, opm parser, opm core and opm autodiff during the last two weeks so I guess it's not an update issue (and it also seems to be solved?)

and since `wells_example.cpp` is located in opm-core I don't believe it is an issue with autodiff. The last hit is `EclipseGrid.cpp` itself.

I'm quite new to OPM and also have limited experience with Linux systems. Searching for "symbol lookup error" I found some advice (http://benohead.com/linux-c-lookup-error-undefined-symbol/) that I tried out:
```
ldd wells_example
```
does not yield any "not found" so I guess I'm not missing any libraries.
```
ldd -r -d wells_example
```
gives the libraries and
```
undefined symbol: ecl_grid_init_actnum_data	(./wells_example)
undefined symbol: ecl_grid_get_zcorn_size	(./wells_example)
undefined symbol: ecl_grid_init_mapaxes_data_double	(./wells_example)
undefined symbol: ecl_grid_alloc_copy	(./wells_example)
undefined symbol: ecl_grid_reset_actnum	(./wells_example)
undefined symbol: ecl_grid_alloc_dxv_dyv_dzv_depthz	(./wells_example)
undefined symbol: ecl_grid_init_coord_data_double	(./wells_example)
undefined symbol: ecl_grid_init_zcorn_data_double	(./wells_example)
undefined symbol: ecl_grid_get_coord_size	(./wells_example)
undefined symbol: ecl_grid_alloc_dx_dy_dz_tops	(./wells_example)
undefined symbol: ecl_grid_use_mapaxes	(./wells_example)
```
so I guess it isn't just `ecl_grid_alloc_dx_dy_dz_tops` that's missing. I don't know how to further debug the problem and any help or advice would be much appreciated. I guess you would need some information about my installation, so please let me know

**Comment by bska** [comment]
>
```
./wells_example: symbol lookup error: ./wells_example: undefined symbol: ecl_grid_alloc_dx_dy_dz_tops
```

Your commands suggest you're using shared libraries.  May I ask **where** (in what directory) you installed the ERT and opm-parser libraries?  In particular, did these libraries go into a system-wide location (e.g., `/usr/local/lib`) or a directory that's specific to your user account (e.g., somewhere below your `${HOME}` directory) and that might not be searched by default during dynamic loading?

What does the command
```
locate libecl.so
```
return?

**Comment by TobiasRitschel** [comment]
When I installed from source, I called

cmake ..
make
make install

which I believe put it in the shared libraries.

locate libecl.so

returns

/home/tobias/.local/share/Trash/files/ert-build.3/lib/x86_64-linux-gnu/libecl.so
/home/tobias/.local/share/Trash/files/ert-build.3/lib/x86_64-linux-gnu/libecl.so.1.0
/home/tobias/.local/share/Trash/files/lib.4/x86_64-linux-gnu/libecl.so
/home/tobias/.local/share/Trash/files/lib.4/x86_64-linux-gnu/libecl.so.1.0
/home/tobias/.local/share/Trash/files/lib.7/x86_64-linux-gnu/libecl.so
/home/tobias/.local/share/Trash/files/lib.7/x86_64-linux-gnu/libecl.so.1.0
/home/tobias/Documents/OPM/ert-build/lib/x86_64-linux-gnu/libecl.so
/home/tobias/Documents/OPM/ert-build/lib/x86_64-linux-gnu/libecl.so.1.0
/usr/lib/x86_64-linux-gnu/libecl.so.1.0
/usr/local/lib/x86_64-linux-gnu/libecl.so
/usr/local/lib/x86_64-linux-gnu/libecl.so.1.0

I guess the "Trash files" are unimportant. There are some in folders specific to my account and as far as I can see two in the system-wide folders.

When I installed OPM and ERT I was having some trouble and in lack of better ideas I manually copied some lib folders into the system-wide folders. I later worked out the problem, but could this pose a problem? I set the LIBRARY_PATH environment variable such that

echo $LIBRARY_PATH

returns

/usr/lib/x86_64-linux-gnu

I just tried adding /usr/lib/x86_64-linux-gnu and /usr/local/lib/x86_64-linux-gnu to LD_LIBRARY_PATH and now I get the following

inputdeck not found. Using default value 'data.data'.
num_psteps not found. Using default value '1'.
stepsize_days not found. Using default value '1'.
Program threw an exception: Deck requires a 'GRID' section
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Deck requires a 'GRID' section
Aborted (core dumped)

To me it seems that altering the LD_LIBRARY_PATH has solved the problem? Thanks for the quick response by the way.

**Comment by joakim-hove** [comment]
>When I installed OPM and ERT I was having some trouble and in lack of better ideas I manually copied some lib folders into the system-wide folders. I later worked out the problem, but could this pose a problem? 

During the build process cmake will embed the path to the shared libraries into the libraries using a method called RPATH, this is to ensure that the newly created libraries/executable can be tested from the build directory without the issues you have had. When you then do 

```txt
make install
```
The libraries will be *relinked*, either by completely removing the RPATH settings or alternatively updating them to what you have configured in the build. So assuming you did not install the libraries with `make install` you will have libraries with incorrect RPATH settings. Using the `LD_LIBRARY_PATH` variable you have been able to override the embedded RPATH setting and get things to work.

So all in all this should work:
1. Make sure to install properly with `sudo make install` after building the various modules.
2. Unset the `LD_LIBRARY_PATH` and things *should* work.

**Comment by bska** [comment]
> I guess the "Trash files" are unimportant.

They are indeed.  The important part is

>
```
/usr/lib/x86_64-linux-gnu/libecl.so.1.0
/usr/local/lib/x86_64-linux-gnu/libecl.so
/usr/local/lib/x86_64-linux-gnu/libecl.so.1.0
```

It's slightly unusual to have the library both in `/usr/lib` and in `/usr/local/lib` unless one is a symbolic link to the other, but I'll pass that by for the moment.  As @joakim-hove says, `sudo make install` **should** do the right thing, but there is one more potential issue that we need to check.

Note: I don't think this is the real issue, but I'd still like to see the output of
```sh
sed -n -e '/include.*\*/s/include//p' /etc/ld.so.conf | \
while read dspec; do
  d=`dirname "${dspec}"`
  echo "--> ${d}"
  ls -1F "${d}"
done
sed -e '/include.*\*/d' /etc/ld.so.conf
```
This will hopefully enable us to exclude ill-configured `ld.so` as an explanation for the issues you've experienced.

**Comment by joakim-hove** [comment]
> It's slightly unusual to have the library both in /usr/lib and in /usr/local/lib

Can it be that you have an old binary installation ( i.e. `.deb` org `.rpm` package?)

**Comment by TobiasRitschel** [comment]
Before trying to install from source, I installed from binaries. I thought it wasn't working because I wasn't linking the libraries correctly. Afterwards I installed from source. As far as I know I have both a binary and a source installation if that's possible. Could this be a problem? I am using Ubuntu 14.04LTS

I cannot figure out how to execute the commands

sed -n -e '/include.*\*/s/include//p' /etc/ld.so.conf | \
while read dspec; do
  d=`dirname "${dspec}"`
  echo "--> ${d}"
  ls -1F "${d}"
done
sed -e '/include.*\*/d' /etc/ld.so.conf

After I've typed done, it returns

d: command not found

Should I be running it from a particular place? sed -e '/include.*\*/d' /etc/ld.so.conf then returns blank. I tried doing the

ccmake / cmake
make
make install

for ERT, opm-parser and opm-core in that order (from build directory siblings) but it doesn't seem to help. It's true that I can run the wells_example with the "GRID section missing" error before I call make install for opm-core. However, after calling "make install" for opm-core the problem persists (I changed back the LD_LIBRARY_PATH variable).

**Comment by bska** [comment]
> I cannot figure out how to execute the commands [omitted]

Copy-paste into a terminal and press `<Enter>`.  Note: that command sequence assumes that you have not changed your shell from the default (typically bash or dash).

**Comment by atgeirr** [comment]
> Before trying to install from source, I installed from binaries.

This may very well create conflicts. The build system may find the libraries it needs in three different places:
 - In /usr/lib, (from the binary packages).
 - In /usr/local/lib (from make install of a module).
 - In the same directory as a sibling.
You must use only one, or it will be very troublesome, especially once you update some modules (and the latest sources are very far from the old binary packages). The ability to find siblings is controversial about some developers, partially because it allows you to mess up this. We should revise the docs to be very clear about this (need to uninstall binary packages before using sources etc.).

There have been some shell scripts made (for Ubuntu 14.04, do not know what you have), at opm-utilities/vagrant, the `clone_and_compile.sh` script may make things easier for you (but you should clean out all installed opm things first from /usr and /usr/local).

**Comment by joakim-hove** [comment]
>As far as I know I have both a binary and a source installation if that's possible. Could this be a problem? 

Yes - I am quite certain that is the problem. What I think happens is that your build process works (more or less) as it should; but at runtime the old (i.e. coming from the binary package) versions of the shared libraries are  located - and in those old versions of e.g. `libecl.so` the symbol you have quoted in the title is missing - it makes sense.

I would strongly recommend that you start with uninstalling the binary packages; and then reconfigure and build.

**Comment by bska** [comment]
>> Before trying to install from source, I installed from binaries.
>
> This may very well create conflicts.

Yes, that's the most likely reason as far as I can tell.  The binary packages for `ert.ecl` on [Launchpad.net](https://launchpad.net/~opm/+archive/ubuntu/ppa/+sourcepub/4172929/+listing-archive-extra) are based on tag `release/2013.10/final2` of the ERT and the `ecl_grid_alloc_dx_dy_dz_tops` symbol (function) is more recent than that--notably from commit Ensembles/ert@a4cd15ea447ffd3b7914353397d1e9b2a41cba67 (PR Ensembles/ert#453, 28th of March 2014).

It'd be good to see the output of
```sh
ldd wells_example | grep libecl
```
because I **suspect** that that will reference the version in `/usr/lib`.

**Comment by TobiasRitschel** [comment]
ldd wells_example | grep libecl

produces

libecl.so.1.0 => /usr/lib/x86_64-linux-gnu/libecl.so.1.0 (0x00007f5487283000)

It seems that you are correct. I'll get right on removing and uninstalling everything and build from source. I'll let you know as soon as I am done and have tested the wells_example.

**Comment by TobiasRitschel** [comment]
By the way

sed -n -e '/include.*\*/s/include//p' /etc/ld.so.conf | \
while read dspec; do
  d=`dirname "${dspec}"`
  echo "--> ${d}"
  ls -1F "${d}"
done
sed -e '/include.*\*/d' /etc/ld.so.conf

produces

--> /etc/ld.so.conf.d
fakeroot-x86_64-linux-gnu.conf
libc.conf
x86_64-linux-gnu.conf
x86_64-linux-gnu_EGL.conf@
x86_64-linux-gnu_GL.conf@
x86_64-linux-gnu_mirclientplatform.conf@
zz_i386-biarch-compat.conf

**Comment by bska** [comment]
> By the way
```sh
sed -n -e '/include.*\*/s/include//p' /etc/ld.so.conf | \
while read dspec; do
  # ... operations
done
```
produces

[a reasonable list of files]

Good!  That is what I expected so we can rule out misconfiguration of the operating system as an explanation.  I'm becoming increasingly convinced that it is the conflict between package-based and source-based installation that is causing your troubles.

I look forward to hearing how the "build from scratch on clean system" exercise pans out.

**Comment by TobiasRitschel** [comment]
I believe I managed to clean the system for packages (using "sudo apt-get remove" and "sudo dpkg --get-selections") and cleaned lib and header files from /usr and /usr/local. I then removed all ERT and OPM files that I downloaded for installing and repeated the cloning from Git and installing using

cmake ..
make
sudo make install

The code compiles but when I try to run I get the following error

./wells_example: error while loading shared libraries: libecl.so.1.0: cannot open shared object file: No such file or directory

and using "ldd wells_example" gives

	linux-vdso.so.1 =>  (0x00007ffffedfe000)
	libecl.so.1.0 => not found
	liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007fbe8c35d000)
	libblas.so.3 => /usr/lib/libblas.so.3 (0x00007fbe8c0df000)
	libboost_regex.so.1.54.0 => /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.54.0 (0x00007fbe8bdd8000)
	libboost_system.so.1.54.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.54.0 (0x00007fbe8bbd4000)
	libboost_filesystem.so.1.54.0 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.54.0 (0x00007fbe8b9bd000)
	libumfpack.so.5.6.2 => /usr/lib/x86_64-linux-gnu/libumfpack.so.5.6.2 (0x00007fbe8b71a000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fbe8b416000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbe8b10f000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fbe8aef9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbe8ab34000)
	libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007fbe8a81a000)
	libicuuc.so.52 => /usr/lib/x86_64-linux-gnu/libicuuc.so.52 (0x00007fbe8a4a1000)
	libicui18n.so.52 => /usr/lib/x86_64-linux-gnu/libicui18n.so.52 (0x00007fbe8a09a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbe89e7b000)
	libamd.so.2.3.1 => /usr/lib/x86_64-linux-gnu/libamd.so.2.3.1 (0x00007fbe89c72000)
	libcholmod.so.2.1.2 => /usr/lib/x86_64-linux-gnu/libcholmod.so.2.1.2 (0x00007fbe8999f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fbe8cb19000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007fbe89762000)
	libicudata.so.52 => /usr/lib/x86_64-linux-gnu/libicudata.so.52 (0x00007fbe87ef5000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbe87cf0000)
	libcolamd.so.2.8.0 => /usr/lib/x86_64-linux-gnu/libcolamd.so.2.8.0 (0x00007fbe87ae9000)
	libcamd.so.2.3.1 => /usr/lib/x86_64-linux-gnu/libcamd.so.2.3.1 (0x00007fbe878de000)
	libccolamd.so.2.8.0 => /usr/lib/x86_64-linux-gnu/libccolamd.so.2.8.0 (0x00007fbe876d4000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fbe874cc000)

where we indeed see that it can't find libecl.so.1.0. Adding /usr/local/lib/x86_64-linux-gnu to LD_LIBRARY_PATH solves the problem. /usr/local/lib/x86_64-linux-gnu is on LIBRARY_PATH. 

It seems that the clean install resolved the problem of the symbol lookup error. I don't know if I did anything wrong on installation. "locate libecl.so" gives

/home/tobias/.local/share/Trash/files/ert-build.3/lib/x86_64-linux-gnu/libecl.so
/home/tobias/.local/share/Trash/files/ert-build.3/lib/x86_64-linux-gnu/libecl.so.1.0
/home/tobias/.local/share/Trash/files/ert-build.4/lib/x86_64-linux-gnu/libecl.so
/home/tobias/.local/share/Trash/files/ert-build.4/lib/x86_64-linux-gnu/libecl.so.1.0
/home/tobias/.local/share/Trash/files/ert.3/devel/lib/x86_64-linux-gnu/libecl.so
/home/tobias/.local/share/Trash/files/ert.3/devel/lib/x86_64-linux-gnu/libecl.so.1.0
/home/tobias/.local/share/Trash/files/lib.4/x86_64-linux-gnu/libecl.so
/home/tobias/.local/share/Trash/files/lib.4/x86_64-linux-gnu/libecl.so.1.0
/home/tobias/.local/share/Trash/files/lib.7/x86_64-linux-gnu/libecl.so
/home/tobias/.local/share/Trash/files/lib.7/x86_64-linux-gnu/libecl.so.1.0
/home/tobias/Documents/OPM/ert-build/lib/x86_64-linux-gnu/libecl.so
/home/tobias/Documents/OPM/ert-build/lib/x86_64-linux-gnu/libecl.so.1.0
/usr/local/lib/x86_64-linux-gnu/libecl.so
/usr/local/lib/x86_64-linux-gnu/libecl.so.1.0

and I've used "sudo updatedb" to remove old locations of libecl.so from this list.

**Comment by bska** [comment]
> `ldd wells_example` gives
```
libecl.so.1.0 => not found
```

Just out of curiosity, what do the commands
```sh
LD_LIBRARY_PATH=/usr/local/lib ldd wells_example | grep libecl
```
and
```sh
cat /etc/ld.so.conf.d/*.conf
```
and
```sh
readelf -d wells_example | grep -E '(RUN|R)PATH'
objdump -x wells_example | grep -E '(RUN|R)PATH'
```
return?

**Comment by bska** [comment]
I'd also like to see the output of
```sh
sed -e 's/  */\ 
/g' CMakeFiles/wells_example.dir/link.txt
```
when run from within the "opm-core" build directory.

**Comment by bska** [comment]
And, if it's not too much trouble, the output of
```sh
g++ -print-search-dirs | tr : \\n | sed -n '/libraries/,$p'
```
as well.

**Comment by TobiasRitschel** [comment]
"LD_LIBRARY_PATH=/usr/local/lib ldd wells_example | grep libecl" gives

	libecl.so.1.0 => not found

"cat /etc/ld.so.conf.d/*.conf" gives

/usr/lib/x86_64-linux-gnu/libfakeroot
# libc default configuration
/usr/local/lib
# Multiarch support
/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/mesa-egl
/usr/lib/x86_64-linux-gnu/mesa
/usr/lib/x86_64-linux-gnu/mir/clientplatform/mesa
# Legacy biarch compatibility support
/lib32
/usr/lib32

"readelf -d wells_example | grep -E '(RUN|R)PATH'" and "objdump -x wells_example | grep -E '(RUN|R)PATH'" gives nothing. I copy pasted

sed -e 's/  */\ 
/g' CMakeFiles/wells_example.dir/link.txt

which gives

sed: -e expression #1, char 8: unterminated `s' command

and lastly "g++ -print-search-dirs | tr : \\n | sed -n '/libraries/,$p'" gives

libraries
 =/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/4.8/
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/
/usr/lib/x86_64-linux-gnu/../lib/
/usr/local/lib/x86_64-linux-gnu/x86_64-linux-gnu/4.8/
/usr/local/lib/x86_64-linux-gnu/x86_64-linux-gnu/
/usr/local/lib/x86_64-linux-gnu/../lib/
/usr/lib/gcc/x86_64-linux-gnu/4.8/
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/lib/x86_64-linux-gnu/4.8/
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/lib/x86_64-linux-gnu/
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/lib/../lib/
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/4.8/
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/
/lib/x86_64-linux-gnu/4.8/
/lib/x86_64-linux-gnu/
/lib/../lib/
/usr/lib/x86_64-linux-gnu/4.8/
/usr/lib/x86_64-linux-gnu/
/usr/lib/../lib/
/usr/lib/x86_64-linux-gnu/
/usr/local/lib/x86_64-linux-gnu/
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/lib/
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../
/lib/
/usr/lib/

It is definitely not too much trouble, I appreciate the help very much.

**Comment by bska** [comment]
>
```
sed: -e expression #1, char 8: unterminated `s' command
```

Sorry.  I was too sloppy with that one.  On the other hand, it's also the one I really wanted to see, so I'd appreciate if you could copy-paste and run
```sh
nl="
"
sed -e "s/  */\\${nl}/g" CMakeFiles/wells_example.dir/link.txt
```
from the build directory of module opm-core.

**Comment by TobiasRitschel** [comment]
Naturally, it returns

/usr/bin/c++
-pipe
-Wall
-Wno-unknown-pragmas
-std=c++11
-O2
-DNDEBUG
-mtune=native
-Wl,--enable-new-dtags
CMakeFiles/wells_example.dir/examples/wells_example.cpp.o
-o
bin/wells_example
-rdynamic
lib/libopmcore.a
-lboost_iostreams
-lumfpack
-lamd
-Wl,-Bstatic
-lsuitesparseconfig
-Wl,-Bdynamic
-lrt
-lsuperlu
-Wl,-Bstatic
-lParser
-lopm-json
-Wl,-Bdynamic
-lboost_filesystem
-lboost_date_time
-lboost_system
-lboost_regex
-lecl
-lecl_well
-lert_geometry
-lert_util
-lz
-llapack
-lblas
-lm
-lpthread
-ldl

**Comment by bska** [comment]
> Naturally

Thanks.  Much appreciated.

> it returns
```
/usr/bin/c++
[...]
-ldl
```

Aha!  Now we're at least getting somewhere.  On my own system I get
```
/usr/bin/g++
-std=c++0x
[...]
-ldl
-Wl,-rpath,/home/bska/work/opm/inst/opt/lib/x86_64-linux-gnu
```
with the distinct difference being that I get the (non-default) location of the ert libraries as a run-path (`-Wl,-rpath,/home/.../x86_64-linux-gnu`) and you don't get anything in particular.  That, in turn, means that "your" version of `wells_example` relies the system configuration to find particular shared libraries, notably the ERT libraries, whereas "mine" uses a run-path derived from information determined during build configuration.

Now, from earlier analysis (`g++ -print-search-dirs`) we know that
```
/usr/local/lib/x86_64-linux-gnu/
```
is searched for library files during compilation/linking.  On the other hand, `cat /etc/ld.so.conf.d/*.conf` indicates that that directory is **not** part of the dynamic linker's library search path.  In other words, there is an inconsistency somewhere and it is most decidedly not your fault.  Rather, this is a problem in the build system of either opm-core or the ert (or in the interaction of both).

Granted, the `make install` target of CMake-derived build systems [does not run `ldconfig`](http://lmgtfy.com/?q=cmake+make+install+ldconfig) where it probably could/should, but on the other hand there is something to be said for using a package manager to do final system install.

I the short term I recommend running
```sh
sudo ldconfig
```
as that will (hopefully!) add `/usr/local/lib/x86_64-linux-gnu/` to the list of directories that the dynamic linker searches for library files at application startup.  Long term, we (the OPM project) need to figure out the proper solution to this problem.

**Comment by TobiasRitschel** [comment]
I tried running "sudo ldconfig" but the problem remains. I forgot to ask, by the way, whether I should delete the build directories and the git directories as locate libecl.so returns a lot of local directories as well?

I also tried running

nl="
"
sed -e "s/  */\\${nl}/g" CMakeFiles/wells_example.dir/link.txt

again but it does not seem to have changed. The same goes for

cat /etc/ld.so.conf.d/*.conf

**Comment by bska** [comment]
> I tried running `sudo ldconfig` but the problem remains

I see.  Would you mind running
```sh
sudo ldconfig  /usr/local/lib/x86_64-linux-gnu/
```
instead?

> I also tried running
```sh
nl="
"
sed -e "s/  */\\${nl}/g" CMakeFiles/wells_example.dir/link.txt
```
again but it does not seem to have changed

That is to be expected.  Running `ldconfig` does not affect the link flags of a build command.  If the `ldconfig` incantation had made a difference you would rater see it in the output of the commands
```sh
cat /etc/ld.so.conf
cat /etc/ld.so.conf.d/*.conf
```

**Comment by TobiasRitschel** [comment]
That did the job. Thanks again for all the help.

**Comment by bska** [comment]
> That did the job.

Good.  I'm glad.

> Thanks again for all the help.

No worries.  Sorry it took so long to diagnose and fix it.

**Comment by TobiasRitschel** [comment]
No problem, I thought it would take longer and it was interesting to learn a bit about the installation process.
