### ISSUE TITLE
Setting up new opm-core project

### ISSUE THREAD

**Issue by rinauoy** [OPM/opm-core#783]
Dear Friends, 

First, I'd like apologise for my ignorance. I am new Linux Ubuntu and OPM. I have managed to set up Ubuntu on virtual box and install opm-core library. I have tried to test tutorial codes (a simple Cartesian grid)  on CodeBlock but it seems to be not working. Codeblock could not find 'opm/core/grid.h' file. I think I haven't managed to link the library properly. 

I appreciate your input and help around this issue. 

Thanks very much. 

Regards, 

Rina

![opmcore](https://cloud.githubusercontent.com/assets/9147160/7100049/ef265596-e03c-11e4-81d8-4f65508d0bd1.PNG)
![opmcoreerror](https://cloud.githubusercontent.com/assets/9147160/7100050/ef275630-e03c-11e4-85b8-70a4d1c8da68.PNG)

**Comment by atgeirr** [comment]
I do not think the libopm-core1-bin package installs the necessary header file, you must install the *-dev packages instead. Also: we are currently in the process of making a new release (2015.04), so the packages will soon get an update!

**Comment by rinauoy** [comment]
Thanks very much. I managed to get it work now. :)

**Comment by atgeirr** [comment]
Good! I'll close the issue then.
