### ISSUE TITLE
Problem with -DDUNE_ROOT?

### ISSUE THREAD

**Issue by qilicun** [OPM/opm-core#796]
I pre-install dune in a local directory
``
/home/liuming/local/dune-2.3.1
``
Actually, this directory looks as follow:
``
bin  include  lib  share
``
But when I pass dune with` -DDUNE_ROOT=/home/liuming/local/dune-2.3.1` to cmake, cmake complain that. 
```
-- Finding package dune-common using module mode
-- Failed to find library "dunecommon" for module dune-common
-- Finding package CxaDemangle using module mode
-- Performing Test HAVE_CXA_DEMANGLE
-- Performing Test HAVE_CXA_DEMANGLE - Success
-- Performing Test HAVE_DUNE_COMMON
-- Performing Test HAVE_DUNE_COMMON - Failed
-- DUNE_COMMON_ROOT = /home/liumimg/local/dune-2.3.1/dune-common
-- Could NOT find dune-common (missing:  dune-common_INCLUDE_DIR dune-common_LIBRARY HAVE_DUNE_COMMON) 
-- Finding package dune-istl using module mode
-- Performing Test HAVE_DUNE_ISTL
-- Performing Test HAVE_DUNE_ISTL - Failed
-- DUNE_ISTL_ROOT = /home/liumimg/local/dune-2.3.1/dune-istl
-- dune-istl prereqs: .;dune-common-NOTFOUND
-- Could NOT find dune-istl (missing:  dune-istl_INCLUDE_DIR HAVE_DUNE_ISTL dune-istl_ALL_PREREQS) 
```
If I remember correctly, `-DDUNE_ROOT` does works well before! Did I mistake something?

**Comment by blattms** [comment]
```
> If I remember correctly, `-DDUNE_ROOT` does works well before! Did I
> mistake something?
```
I guess you have to use DUNE_COMMON_ROOT and DUNE_ISTL_ROOT or more
general ```${MODULE}_ROOT``` where module is te uppercase name with
underlines instead of dashes.

**Comment by qilicun** [comment]
@blattms 
I guess too, but when did opm changes that from DUNE_ROOT to DUNE_${MODULE}_ROOT? But by all means, thank you.

**Comment by alfbr** [comment]
For Dune 2.3.1 at least is suffices to do -DDUNE_ROOT. Your library doesn't look correct, have a look in /project/res/x86_64_RH_5/share/opm/dune.

**Comment by qilicun** [comment]
@alfbr 

Yes, in that directory, dune was installed by individual module.But the strange thing is that I install dune-2.3.1 in `/project/eor/user/liuming/local/dune-2.3.1/` in STATOIL machine, with `DUNE_ROOT` it works well

``
Found dune-common: /project/eor/user/liuming/local/dune-2.3.1/include  
-- Version 2.3.1 of dune-common from /project/eor/user/liuming/local/dune-2.3.1/lib/dunecontrol/dune-common/dune.module
``

But when I do the same thing in my laptop last night, the error happened.  
There could be one reason, in statoil machine, I compile and install dune with *dunecontrol*(I'm not sure, long time ago), but in my laptop dune was compiled and installed with *cmake*.  I need to check.

**Comment by alfbr** [comment]
I believe it was done with cmake in Statoil too, that should not make a difference. Just check though.

**Comment by qilicun** [comment]
Thanks the discussion, the problem was solved.

**Comment by blattms** [comment]
Other people might experience the same problem. Would you mind telling
how it was solved?

**Comment by qilicun** [comment]
@blattms 

I totally have no idea... install all the dune module in a same directory, the sub directories are 
``
bin  include  lib  lib64  share
``
other than module name, with `DUNE_ROOT`, it works well in statoil machine, without any problem.
But the strange thing happened in my laptop, I need to check it again after work.
