### ISSUE TITLE
mpi.h couldn't be found

### ISSUE THREAD

**Issue by YingfangZhou** [OPM/opm-core#817]
I was trying to compile opm-core and got the following error:
![image](https://cloud.githubusercontent.com/assets/9039553/8090303/0a6b8348-0fa5-11e5-84d1-7e1ea742829e.png)

I have located mpi.h and it was found in several locations:
![image](https://cloud.githubusercontent.com/assets/9039553/8090229/acf36578-0fa4-11e5-8cd4-1bf904cf8790.png)

Do you have any suggestion on the issue? or is it possible to compile opm-core without petsc?

Best wishes

**Comment by bska** [comment]
> Is it possible to compile opm-core without PETSc

Yes, pass `-DCMAKE_DISABLE_FIND_PACKAGE_PETSc` (note lower case `c` at the end) as an option on the `cmake` command line used to set up the build tree for opm-core.

**Comment by YingfangZhou** [comment]
@bska Should I use it as below
cmake -DCMAKE_DISABLE_FIND _PACKAGE_PETSc ../../opm-core/ & make & sudo make install

**Comment by YingfangZhou** [comment]
@bska 
I am using the following command to compile without PETSc
![image](https://cloud.githubusercontent.com/assets/9039553/8093218/946279a0-0fb7-11e5-9446-9fc2bcf38868.png)

and it seems the PETSc package still there for compiling.
![image](https://cloud.githubusercontent.com/assets/9039553/8093243/baf79780-0fb7-11e5-8fbb-0b08167d93c7.png)

**Comment by bska** [comment]
> Should I use it as below
```sh
cmake -DCMAKE_DISABLE_FIND _PACKAGE_PETSc ../../opm-core/ && make && sudo make install
```

Yes, that is essentially it.  The `-DCMAKE_DISABLE_FIND_PACKAGE_PETSc` flag cannot be passed through the `configure` script.

**Comment by YingfangZhou** [comment]
@bska 
I am using the command as you suggested, 
~/OPM/opm-core-build$ chmod ../../opm-core/configure & cmake -DCMAKE_DISABLE_FIND _PACKAGE_PETSc ../../opm-core/ & make & sudo make install
and it seems the format was wrong and gives the following messages:
[1] 46498
[2] 46499
[3] 46500
chmod: missing operand after â../../opm-core/configureâ
Try 'chmod --help' for more information.
make: *** No targets specified and no makefile found. Stop.
Parse error in command line argument: -DCMAKE_DISABLE_FIND
Should be: VAR:type=value
CMake Error: No cmake script provided.
CMake Error: Problem processing arguments. Aborting.

[sudo] password for yz7609:
make: *** No rule to make target `install'. Stop.
[1]   Exit 1                  chmod ../../opm-core/configure
[2]-  Exit 1                  cmake -DCMAKE_DISABLE_FIND _PACKAGE_PETSc ../../opm-core/
[3]+  Exit 2                  make

Many thanks for your kindness help.

**Comment by bska** [comment]
> I am using the command as you suggested,

The `&` (ampersand) characters of that command must rather be `&&` (double ampersand).

**Comment by bska** [comment]
Oh, and you don't need the `configure` command at all when you invoke `cmake` directly.  You should say something along the lines of
```sh
cmake -DCMAKE_DISABLE_FIND_PACKAGE_PETSc ../../opm-core && make && sudo make install
```

**Comment by YingfangZhou** [comment]
@bska 
If I am using the && and it was wrong with commond chmod:
~/OPM/opm-core-build$ chmod ../../opm-core/configure && cmake -DCMAKE_DISABLE_FIND _PACKAGE_PETSc ../../opm-core/ && make && sudo make install
chmod: missing operand after â../../opm-core/configureâ
Try 'chmod --help' for more information.
yz7609@ese-zhou:~/OPM/opm-core-build$

**Comment by bska** [comment]
> it was wrong with commond `chmod`:

Yeah, don't bother that.  Just say
```sh
cmake -DCMAKE_DISABLE_FIND_PACKAGE_PETSc ../../opm-core && make && sudo make install
```

**Comment by YingfangZhou** [comment]
@bska 
~/OPM/opm-core-build$ cmake -DCMAKE_DISABLE_FIND_PACKAGE_PETSc ../../opm-core && make && sudo make install
Parse error in command line argument: -DCMAKE_DISABLE_FIND_PACKAGE_PETSc
Should be: VAR:type=value
CMake Error: No cmake script provided.
CMake Error: Problem processing arguments. Aborting.

**Comment by bska** [comment]
> Should be: `VAR:type=value`

Ah, yes.  Sorry about that.  You need to say
```sh
cmake -DCMAKE_DISABLE_FIND_PACKAGE_PETSc:BOOL=TRUE ../../opm-core && make && sudo make install
```
instead
