### ISSUE TITLE
Does opm-core depend on opm-material now?

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-core#835]
A cmake with no parameter failed with ert and opm-parser and opm-core updated. 

The error message is as following. I do not have opm-material installed. 

```
-- Found opm-parser: /home/kaib/OPM/build/opm-parser;/home/kaib/OPM/build/opm-parser-build/generated-source/include;/usr/include;/usr/local/include;/usr/include  
-- Finding package opm-material using module mode
-- Performing Test HAVE_OPM_MATERIAL
-- Performing Test HAVE_OPM_MATERIAL - Failed
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find opm-material (missing: opm-material_INCLUDE_DIR
  HAVE_OPM_MATERIAL)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /home/kaib/OPM/build/opm-cmake/cmake/Modules/OpmPackage.cmake:358 (find_package_handle_standard_args)
  /home/kaib/OPM/build/opm-cmake/cmake/Modules/Findopm-material.cmake:16 (find_opm_package)
  /home/kaib/OPM/build/opm-cmake/cmake/Modules/OpmFind.cmake:147 (find_package)
  /home/kaib/OPM/build/opm-cmake/cmake/Modules/OpmFind.cmake:211 (find_and_append_package_to)
  /home/kaib/OPM/build/opm-cmake/cmake/Modules/OpmLibMain.cmake:104 (find_and_append_package_list_to)
  CMakeLists.txt:156 (include)
```

**Comment by andlaus** [comment]
yes it now depends on opm-material. (cf. OPM/opm-cmake#27 ). until #834 is merged, it is not yet used by the code, though.

**Comment by GitPaean** [comment]
Thanks. What is the potential order of the dependency then? `opm-material` should depend on `opm-parser` or `opm-parser` should depend on `opm-material` later? or they are not dependent on each other?

**Comment by andlaus** [comment]
`opm-material` optionally depends in `opm-parser` but `opm-parser` does (and probably will never) know anything about `opm-material`. on the other hand, `opm-core` now has a hard dependency on both modules, so the order is `parser` -> `material` -> `core`

**Comment by andlaus** [comment]
also note that since `opm-core` is a hard dependency of `dune-cornerpoint`, you now need `opm-material` to build `dune-cornerpoint` even though the grid code in core is not and will not be dependent on `opm-material`. IMO this means that the grid parts should be moved from `opm-core` into `dune-cornerpoint` with possibly renaming `dune-cornerpoint` to `opm-grid` (or similar).

**Comment by GitPaean** [comment]
Thanks for the information. I will close the issue now.
