### ISSUE TITLE
Cells with zero PORO or NTG should be treated as inactive.

### ISSUE THREAD

**Issue by osae** [OPM/opm-core#878]
This seems currently not the case in opm unless MINPV is active, confer PR #861

**Comment by rolk** [comment]
This seems related to #455; maybe the fix here can also bring resolution to that case.

**Comment by pgdr** [comment]
fix proposed by @joakim-hove  in OPM/opm-parser#808

**Comment by pgdr** [comment]
Fix #808 merged.  Closing this.  Reopen if necessary.
