### ISSUE TITLE
Get faceIdx's position in half transmissibility array?

### ISSUE THREAD

**Issue by qilicun** [OPM/opm-core#891]
Hello,
This issue bothers me a lot, that is how could we get the index of half transmissibility for a face with Opm::AutodiffGrid or Opm::UgGridHelpers? 
To be specified, for original unstructuredGrid if we have a cell index cellIdx, and a face index faceIdx, we can get the index as following(python codes):

```python
idx = list(global_cell).index(cellIdx)
for i in range(cell_facepos[idx], cell_facepos[idx+1])：
    f = cell_faces[i]
    if f == faceIdx:
        return i
```

For Opm::AutodiffGrid or Opm::UgGridHelpers, I also did a try, that is to build a map between faceIdx and cellFaceIdx, as below,

```c
 int cellFaceIdx = 0;
 auto cell_faces = Opm::UgGridHelpers::cell2Faces(grid);
 std::unordered_map<int, int> idxmap;
for (int cell = 0; cell < nc; ++cell) {
    auto cellFacesRange = cell_faces[cell];
     for (auto cellFaceIter = cellFacesRange.begin(); cellFaceIter != cellFacesRange.end(); ++cellFaceIter, ++cellFaceIdx) {
         idxmap.insert(std::make_pair(*cellFaceIter, cellFaceIdx));
      }
        
```

Then for a cellIdx and faceIdx, through the map, we can get the cellFaceIdx.
```c
    auto cell_faces = cell2Faces(grid);
    auto cellFaces = cell_faces[cellIdx]
    for (auto cellFaceIter = cellFaces.begin(); cellFaceIter != cellFaces.end(); ++cellFaceIter) {
        if (*cellFaceIter == faceIdx) {
            index = idxmap.at(faceIdx);
        }
    }
    return index
       
```

But some tests show that it will return the wrong cellFaceIdx. So I'm wondering is there something wrong in the above codes or is there any convenient way to get that index? Thanks!

**Comment by qilicun** [comment]
Sorry for push the wrong button, some more sentences need to be added,

**Comment by bska** [comment]
I always use something akin to the following when I need that mapping
```C++
std::vector<int> hf_ix(2 * numFaces(G), -1);
const auto& f2c = faceCells(G);
const auto& cf = cell2Faces(G);

for (int c = 0, i = 0, nc = numCells(G); c < nc; ++c) {
    for (const auto& f : cf[c]) {
        const auto off = 0 + (f2c(f, 0) != c);
        hf_ix[2*f + off] = i++;
    }
}
```
Then, to look up the half-face index given a pair of cell and face indices becomes simply
```C++
auto hf = hf_ix[2*f + (f2c(f, 0) != c)];
```

**Comment by qilicun** [comment]
@bska 

Your implementation is much easier and clear!,Thanks!
