### ISSUE TITLE
ACTNUM with cartesian grid 

### ISSUE THREAD

**Issue by qilicun** [OPM/opm-core#898]
Hi,

I'm making the tests for pinch processor, I suddenly found that iopm will not creat ACTNUM for cartesian grid, that means MinvpProcessor will not work also. Since this array will be empty, the following error will happen when we specify MINPV keyword together cartesian grid.
```
project/eor/user/liuming/opm/opm-core/opm/core/grid/MinpvProcessor.hpp:96] Wrong size of ACTNUM input, must have one element per logical cartesian cel
```

**Comment by bska** [comment]
We used to treat an empty `ACTNUM` array as "all cells active".  The constructors of Cartesian grids assume that convention.  To be honest, I don't really know what the correct solution is here.  Would you mind testing the change below?

```diff
diff --git a/opm/core/grid/MinpvProcessor.hpp b/opm/core/grid/MinpvProcessor.hpp
index 072a29b..9ba8379 100644
--- a/opm/core/grid/MinpvProcessor.hpp
+++ b/opm/core/grid/MinpvProcessor.hpp
@@ -92,7 +92,7 @@ namespace Opm
         if (pv.size() != log_size) {
             OPM_THROW(std::runtime_error, "Wrong size of PORV input, must have one element per logical cartesian cell.");
         }
-        if (actnum.size() != log_size) {
+        if (!actnum.empty() && (actnum.size() != log_size)) {
             OPM_THROW(std::runtime_error, "Wrong size of ACTNUM input, must have one element per logical cartesian cell.");
         }
 
@@ -101,7 +101,7 @@ namespace Opm
             for (int jj = 0; jj < dims_[1]; ++jj) {
                 for (int ii = 0; ii < dims_[0]; ++ii) {
                     const int c = ii + dims_[0] * (jj + dims_[1] * kk);
-                    if (pv[c] < minpv && actnum[c]) {
+                    if (pv[c] < minpv && (actnum.empty() || actnum[c])) {
                         // Move deeper (higher k) coordinates to lower k coordinates.
                         std::array<double, 8> cz = getCellZcorn(ii, jj, kk, zcorn);
                         for (int count = 0; count < 4; ++count) {
```

**Comment by qilicun** [comment]
@bska 
I think your modification will work, will test later. I'm thinking the same modification needs to be made for PinchProcessor.

>We used to treat an empty ACTNUM array as "all cells active".

This hidden assumption will cause confusion for some people like me. Is there any possibility to add warnings when some codes needs to access to this array with cartesian grid?

**Comment by qilicun** [comment]
@bska 
That works,thanks.

I'm thinking the following fix.
```c
 cartsize = cartDims[0]*cartDims[1]*cartDims[2];
 nc = numCells(grid);
 if ((cartsize == nc) && actnum.empty()) {
   actnum.assign(nc, 1);
}

```
