### ISSUE TITLE
Missing extrapolation of unsaturated data for PVTG (live gas)

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-core#901]
Apparently we do not currently extrapolate to data points without explicitly given unsaturated data. This is done for PVTO, but not PVTG.

**Comment by bska** [comment]
> Apparently we do not currently extrapolate to data points without explicitly given unsaturated data.

That is correct.  We do not do this.

> This is done for PVTO, but not PVTG.

Also correct.  The trouble, however, is that there is no easy algorithm for expanding the PVTG data according to the requirement that expansion satisfy piecewise constant compressibility.  The main reason is that undersaturated PVTG data is tabulated in terms of decreasing Rv at constant pressure whereas undersaturated PVTO is tabulated in terms of increasing Po at constant Rs.  This means that pressure derivatives are trivially accessible in PVTO but not in PVTG.

**Comment by atgeirr** [comment]
Seems to be resolved, closing.
