### ISSUE TITLE
Question about running case from Tutorials

### ISSUE THREAD

**Issue by Tyuan81** [OPM/opm-core#923]
Hi, I got some problems when trying to run the case "A simple cartesian grid" from tutorials. When I compile the cpp, there are some errors as follows:
```
test_grid.cpp:(.text+0xd2): undefined reference to `Opm::GridManager::GridManager(int, int, int, double, double, double)'
test_grid.cpp:(.text+0x115): undefined reference to `Opm::GridManager::c_grid() const'
test_grid.cpp:(.text+0x12e): undefined reference to `Opm::writeVtkData(UnstructuredGrid const&, std::map<std::string, std::vector<double, std::allocator<double> > const*, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<double, std::allocator<double> > const*> > > const&, std::ostream&)'
test_grid.cpp:(.text+0x15b): undefined reference to `Opm::GridManager::~GridManager()'
test_grid.cpp:(.text+0x1bb): undefined reference to `Opm::GridManager::~GridManager()'
```

**Comment by atgeirr** [comment]
Sorry for late reply, I did not notice until now. It looks like you have trouble linking with the opm-core library, if you are manually compiling you should add something like (assuming you use gcc):
```
g++ ... -lopmcore -L<library path> ...
```
where the library path is the location of libopmcore.a (usually found in the lib/ dir of your build directory if you compiled opm-core yourself).

Does this fix your problem?

**Comment by atgeirr** [comment]
No reply, assuming solved. Closing.
