### ISSUE TITLE
cannot plot FOE (Field Oil Recovery)

### ISSUE THREAD

**Issue by imperial-1** [OPM/opm-core#981]
I run some simulations on OPM, I wanted to plot the Field Oil Recovery. In order to do that I created a file that I called foe.py (see below) and I placed it in the folder ert/devel/python/python/ert/ecl. The name of the file was added to the CMakeLists.txt present in the same folder as foe.py. The ert program was then compiled using cmake and make.

After that procedure I was not able to see the "foip vs date" appear on the Terminal (I'm using Ubuntu).

foe.py file:

#!/usr/bin/env python
import sys
from ert.ecl import EclGrid, EclFile
 
base_name = sys.argv[1]
grid = EclGrid("%s.EGRID")
rst_file = EclFile("%s.UNRST") 
 
 
for date in rst_file.dates:
     rst_file.select_restart_section( sim_time = date )
     swat = rst_file[SWAT][0]
     sgas = rst_file[SGAS][0]
     rst_file.select_global()
 
     soil = 1 - swat - sgas
 
     foip = 0
     for index in range(len(soil)):
          cell_volume = grid.cell_volume( active_index = index )
          foip += cell_volume * soil[index]
 
     print "Date:%s  FOIP:%g" % (date , foip)

**Comment by joakim-hove** [comment]
This is ert/python details not really relevant to `opm-core`. I am closing this issue - and encourage you to continue here: https://github.com/Ensembles/ert/issues/1032
