### ISSUE TITLE
Plotting WWCT 

### ISSUE THREAD

**Issue by imperial-1** [OPM/opm-core#986]
Dear all,

I would like to plot Water Cut using ert. Do I need to modify the ert scripts to do that?

Best wishes,

Mansour

**Comment by joakim-hove** [comment]
Take a look at this Python script: https://github.com/OPM/opm-utilities/blob/master/summaryplot

**Comment by imperial-1** [comment]
The problem is not only how to plot it. But WWCT is not read by ert from ECLIPSE file. When I do in the terminal ecl_summary --list  MyCASE, WWCT does not appear.

**Comment by joakim-hove** [comment]
Well - there is no 'WWCT' in the output; the watercut must be qualified by a well name: "WWCT:WELLX" to get the watercut in well *WELLX'.

**Comment by imperial-1** [comment]
What do you mean by output? Is it the summary file? I put in the summary file:

WWCT 
PROD1/

Nothing has changes

**Comment by joakim-hove** [comment]
> What do you mean by output? Is it the summary file?

Yes - the summary file is the output - NB: When I say summary file I mean the `CASE.SMSPEC` and `CASE.UNSMRY` files *generated* by the simulation.

> I put in the summary file:

No - you do *not* put that in the summary file; you put in the summary section of the input file - which is something completely different.


> Nothing has changes

No - as I have already explained `flow` does not yet consider the SUMMARY section - at all. But - `WWCT:PROD1` should still be output but default - I think.

**Comment by imperial-1** [comment]
thank you, I understood but: it seems that WWCT:PROD1 is no generate, when I do: ecl_summary -list MY_CASE, I have this:


TIME                     WBHP:INJE01              WBHP:PROD01              WGIR:INJE01              WGIR:PROD01
WGIT:INJE01              WGIT:PROD01              WGPR:INJE01              WGPR:PROD01              WGPT:INJE01
WGPT:PROD01              WOIR:INJE01              WOIR:PROD01              WOIT:INJE01              WOIT:PROD01
WOPR:INJE01              WOPR:PROD01              WOPT:INJE01              WOPT:PROD01              WWIR:INJE01
WWIR:PROD01              WWIT:INJE01              WWIT:PROD01              WWPR:INJE01              WWPR:PROD01
WWPT:INJE01              WWPT:PROD01



and WWCT:PROD1 does not appear.


________________________________
De : Joakim Hove <notifications@github.com>
Envoyé : vendredi 1 avril 2016 13:13
À : OPM/opm-core
Cc : Khelifa, mansour
Objet : Re: [OPM/opm-core] Plotting WWCT (#986)


What do you mean by output? Is it the summary file?

Yes - the summary file is the output - NB: When I say summary file I mean the CASE.SMSPEC and CASE.UNSMRY files generated by the simulation.

I put in the summary file:

No - you do not put that in the summary file; you put in the summary section of the input file - which is something completely different.

Nothing has changes

No - as I have already explained flow does not yet consider the SUMMARY section - at all. But - WWCT:PROD1 should still be output but default - I think.

-

**Comment by atgeirr** [comment]
I cannot find the WWCT either in output from Flow, I suggest you compute the water cut from the WOPR, WGPR and WWPR data (which are written by Flow currently) as a workaround.

In the longer term, Flow will honor large parts of the specifications in the SUMMARY section of the input deck, that work is underway in the opm-output module.

I will close this issue as resolved. If for some reason the workaround proposed does not work for you @imperial-1, feel free to reopen it and ask more questions.
