### ISSUE TITLE
OPM-core broken?

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-core#996]
```
508 /home/kaib/software/petsc-3.6.2/arch-linux2-c-debug/bin/mpicxx   -DDUNE_COMMON_FIELDVECTOR_SIZE_IS_METHOD=1 -DHAVE_CONFIG_H=1 -DSILENCE_EXTERNAL_WARNINGS -pipe -std=c++0x -pedantic -Wall -Wextra -Wformat-nonliteral -Wcast-align -Wpointer-arith -Wmissing-declarations -Wcast-qual     -Wshadow -Wwrite-strings -Wchar-subscripts -Wredundant-decls -Wno-unknown-pragmas -std=c++11 -O2 -g -fno-omit-frame-pointer -march=native -mtune=native -DDEBUG -fPIC -I/home/kaib/OPM-devel/debug/opm-core-build -I/home/kaib/OPM-devel/debug/opm-core -I/usr/include/suitesparse -I    /usr/include/superlu -I/usr/local/include -I/home/kaib/software/petsc-3.6.2/arch-linux2-c-debug/include -I/home/kaib/local/dune2.3.1/release_mpi/include -I/home/kaib/OPM-devel/debug/opm-common -I/home/kaib/OPM-devel/debug/opm-parser -I/home/kaib/OPM-devel/debug/opm-parser-build    /generated-source/include -I/home/kaib/OPM-devel/debug/opm-material    -o CMakeFiles/opmcore.dir/opm/core/props/rock/RockBasic.cpp.o -c /home/kaib/OPM-devel/debug/opm-core/opm/core/props/rock/RockBasic.cpp
509 In file included from /home/kaib/OPM-devel/debug/opm-core/opm/core/props/rock/RockFromDeck.hpp:23:0,
510                  from /home/kaib/OPM-devel/debug/opm-core/opm/core/props/BlackoilPropertiesFromDeck.hpp:25,
511                  from /home/kaib/OPM-devel/debug/opm-core/opm/core/props/BlackoilPropertiesFromDeck.cpp:21:
512 /home/kaib/OPM-devel/debug/opm-parser/opm/parser/eclipse/EclipseState/EclipseState.hpp:175:26: error: field ‘m_messageContainer’ has incomplete type
513          MessageContainer m_messageContainer;
514                           ^
515 /usr/bin/cmake -E cmake_progress_report /home/kaib/OPM-devel/debug/opm-core-build/CMakeFiles 51
516 [ 48%] Building CXX object CMakeFiles/opmcore.dir/opm/core/props/rock/RockCompressibility.cpp.o
517 /home/kaib/software/petsc-3.6.2/arch-linux2-c-debug/bin/mpicxx   -DDUNE_COMMON_FIELDVECTOR_SIZE_IS_METHOD=1 -D
```

**Comment by dr-robertk** [comment]
HI Kai,

I have the same problem and I fixed it locally by adding

#include <opm/parser/eclipse/Parser/MessageContainer.hpp>

to

opm/parser/eclipse/EclipseState/EclipseState.hpp

I guess some experts have to take a look.

Best,

Rob


On 04/12/2016 12:24 PM, Kai Bao wrote:
> |508 /home/kaib/software/petsc-3.6.2/arch-linux2-c-debug/bin/mpicxx
> -DDUNE_COMMON_FIELDVECTOR_SIZE_IS_METHOD=1 -DHAVE_CONFIG_H=1
> -DSILENCE_EXTERNAL_WARNINGS -pipe -std=c++0x -pedantic -Wall -Wextra
> -Wformat-nonliteral -Wcast-align -Wpointer-arith -Wmissing-declarations
> -Wcast-qual -Wshadow -Wwrite-strings -Wchar-subscripts -Wredundant-decls
> -Wno-unknown-pragmas -std=c++11 -O2 -g -fno-omit-frame-pointer
> -march=native -mtune=native -DDEBUG -fPIC
> -I/home/kaib/OPM-devel/debug/opm-core-build
> -I/home/kaib/OPM-devel/debug/opm-core -I/usr/include/suitesparse -I
> /usr/include/superlu -I/usr/local/include
> -I/home/kaib/software/petsc-3.6.2/arch-linux2-c-debug/include
> -I/home/kaib/local/dune2.3.1/release_mpi/include
> -I/home/kaib/OPM-devel/debug/opm-common
> -I/home/kaib/OPM-devel/debug/opm-parser
> -I/home/kaib/OPM-devel/debug/opm-parser-build /generated-source/include
> -I/home/kaib/OPM-devel/debug/opm-material -o
> CMakeFiles/opmcore.dir/opm/core/props/rock/RockBasic.cpp.o -c
> /home/kaib/OPM-devel/debug/opm-core/opm/core/props/rock/RockBasic.cpp
> 509 In file included from
> /home/kaib/OPM-devel/debug/opm-core/opm/core/props/rock/RockFromDeck.hpp:23:0,
> 510 from
> /home/kaib/OPM-devel/debug/opm-core/opm/core/props/BlackoilPropertiesFromDeck.hpp:25,
> 511 from
> /home/kaib/OPM-devel/debug/opm-core/opm/core/props/BlackoilPropertiesFromDeck.cpp:21:
> 512
> /home/kaib/OPM-devel/debug/opm-parser/opm/parser/eclipse/EclipseState/EclipseState.hpp:175:26:
> error: field ‘m_messageContainer’ has incomplete type 513
> MessageContainer m_messageContainer; 514 ^ 515 /usr/bin/cmake -E
> cmake_progress_report
> /home/kaib/OPM-devel/debug/opm-core-build/CMakeFiles 51 516 [ 48%]
> Building CXX object
> CMakeFiles/opmcore.dir/opm/core/props/rock/RockCompressibility.cpp.o 517
> /home/kaib/software/petsc-3.6.2/arch-linux2-c-debug/bin/mpicxx
> -DDUNE_COMMON_FIELDVECTOR_SIZE_IS_METHOD=1 -D |
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OPM/opm-core/issues/996>
> 

-- 

Dr. Robert Kloefkorn

Senior Research Scientist | http://www.iris.no
International Research Institute of Stavanger
Postboks 8046 | 4068 Stavanger
Phone: +47 482 93 024

**Comment by joakim-hove** [comment]
Ok - this is my fault. Fix coming.

**Comment by joakim-hove** [comment]
OK - this should be fixed with: https://github.com/OPM/opm-parser/pull/755
